### ISSUE TITLE
AttributeError: module 'kenlm' has no attribute 'LanguageModel'

### ISSUE THREAD

**Issue by droussis** [bitextor/monocleaner#6]
Hi and thank you for your work.

When I try to run monocleaner I get the following error:
`AttributeError: module 'kenlm' has no attribute 'LanguageModel'`

Do you have any idea how can I fix this?

**Comment by droussis** [comment]
Fixed it by following these additional steps:

- nano kenlm/setup.py
- Changed 18 to max_order = os.getenv("MAX_ORDER", "7")
- pip install kenlm/

**Comment by ZJaume** [comment]
Hi, did you follow the installation instructions and installed kenlm with this?
```
pip install --config-settings="--build-option=--max_order=7" .
```

**Comment by droussis** [comment]
> Hi, did you follow the installation instructions and installed kenlm with this?
> 
> ```
> pip install --config-settings="--build-option=--max_order=7" .
> ```

It didn't work for me. That's why I tried the workaround.

**Comment by ZJaume** [comment]
If you got `Unrecognized option --config-settings` that is due to an old pip version.
